apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/app-of-apps-demo.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Children apps
  sources:
    - repoURL: https://github.com/example/app-of-apps-demo.git
      targetRevision: HEAD
      path: apps/front-app.yaml
    - repoURL: https://github.com/example/app-of-apps-demo.git
      targetRevision: HEAD
      path: apps/back-app.yaml
    - repoURL: https://github.com/example/app-of-apps-demo.git
      targetRevision: HEAD
      path: apps/database-app.yaml
