apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-backend
  labels:
    app: dummy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-backend
  template:
    metadata:
      labels:
        app: dummy-backend
    spec:
      containers:
      - name: dummy-backend
        image: ealen/echo-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-backend
spec:
  selector:
    app: dummy-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
